= Hackerland Radio Transmitters

Hackerland is a one-dimensional city with N houses, where each house i is located at some x~i~ on the x-axis.
The Mayor wants to install radio transmitters on the roofs of the city's houses. Each transmitter has a range, k,
meaning it can transmit a signal to all houses <= k units of distance away.

Given a map of Hackerland and the value of k, can you find and print the minimum number of transmitters needed to cover
every house in the city? (Every house must be covered by at least one transmitter) Each transmitter must be installed
on top of an existing house.

== Input Format
The first line contains two space-separated integers describing the respective values of  (the number of houses in Hackerland) and  (the range of each transmitter).
The second line contains  space-separated integers describing the respective locations of each house (i.e., ).

== Constraints

|===
| 1 <= n,k <= 10^5^
| 1 <= x~i~ <= 10^5^
| There may be more than one house at the same location.
|===

== Subtasks

|===
| 1 <= n <= 1000 for 50% of the maximum score.
|===

== Output Format

Print a single integer denoting the minimum number of transmitters needed to cover all the houses.

== Sample Input
5 1 +
1 2 3 4 5 +

== Sample Output
2