= Gridland Metro

The city of Gridland is represented as an _n x m_ matrix where the rows are numbered from 1 to _n_ and the columns are numbered from 1 to _m_.

Gridland has a network of train tracks that always run in straight horizontal lines along a row. In other words, the start and end points of a train track are _(r, c1)_ and _(r, c2)_, where r represents the row number,_c1_ represents the starting column, and _c2_ represents the ending column of the train track.

The mayor of Gridland is surveying the city to determine the number of locations where lampposts can be placed. A lamppost can be placed in any cell that is not occupied by a train track.

Given a map of Gridland and its k train tracks, find and print the number of cells where the mayor can place lampposts.

*Note:* A train track may (or may not) overlap other train tracks within the same row.

== Input Format
The first line contains three space-separated integers describing the respective values of _n_ (the number of rows), _m_ (the number of columns), and  _k_ (the number of train tracks).
Each line _i_ of the _k_ subsequent lines contains three space-separated integers describing the respective values of _r_, _c1_, _c2_ and  that define a train track.

== Constraints
|===
| 1 <= n,m <= 10^9^
| 0 <= k <= 1000
| 1 <= r <= n
| 1 <= c~1~ <= c~2~ <= m
|===

== Output Format
Print a single integer denoting the number of cells where the mayor can install lampposts.

== Sample Input
4 4 3 +
2 2 3 +
3 1 4 +
4 4 4 +

== Sample Output
9

== Explanation

|===
|Red |Red |Red |Red
|Red |Yellow |Yellow |Red
|Green |Green |Green |Green
|Red |Red |Red |Blue
|===

In the diagram above, the yellow cells denote the first train track, green denotes the second, and blue denotes the third. Lampposts can be placed in any of the nine red cells, so we print 9 as our answer.